### ISSUE TITLE
Dark Mode for Definition window in both (desktop + Android )

### ISSUE THREAD

**Issue by Aang488** [igorlogius/dbl-click-dict#1]
![image](https://user-images.githubusercontent.com/79444969/234576296-cfa7baea-f119-4383-b456-a7ab18126eb5.png)

**Comment by igorlogius** [comment]
I'll see what i can do. I expect this to be easily done, i'll see how wrong my assumption is in the upcoming days.

**Comment by igorlogius** [comment]
Since i am a very very lazy person i went with the easiest option and just changed the popup background color to be lightgray.

![Screenshot_2023-04-27_01-08-16](https://user-images.githubusercontent.com/67047467/234721481-affa7bb1-8167-473c-bcab-9df0db1cfaac.png)

That should be fine for either a light or a dark theme.

**Comment by Aang488** [comment]
I appreciate your quick remedy, I think grey is also a good color to try. Do you have any plans of implementing dark mode in pop up in the future?

**Comment by igorlogius** [comment]
> Do you have any plans of implementing dark mode in pop up in the future?

Yes my ideal solution is to just use the browser provided CSS styles, which automatically follows the themes. The issue here is ... i've yet not work with this mechanic but i plan to look into this in the future.
